substitutions:
  devicename: quooker
  upper_devicename: "Quooker"

packages:
  common: !include common/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "$upper_devicename Power Button"
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "$upper_devicename Status"

light:
  - platform: binary
    id: led
    output: led_output

switch:    
  - platform: gpio
    pin: 
      number: GPIO12
    name: Relay
    id: relay
    restore_mode:  ALWAYS_ON
    on_turn_on:
      then:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led
output:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    id: led_output
  