esphome:
  name: test
  friendly_name: Test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "OEgqZsTwdq3a8Ff8Az9vkd8+pkgJ4jtAwsbGB51xtKY="

ota:
  - platform: esphome
    password: "52fdfab031b9d48047a7e529a12694a2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "zUEUkNiaF4wc"

captive_portal:

# Example configuration entry
i2c:
  sda: 32
  scl: 33
  scan: true

font:
  - file: "gfonts://Roboto"
    id: small
    size: 8

  - file: "gfonts://Roboto"
    id: medium
    size: 48

  - file: "gfonts://Roboto"
    id: large
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(medium), "Hello World!");    