packages:
  common: !include ../common/esp32-wrover.yaml

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Modbus RS485 from here
uart:
  id: mod_bus
  tx_pin: GPIO16
  rx_pin: GPIO04
  baud_rate: 9600
  parity: even
  stop_bits: 1
  debug:

modbus:
  flow_control_pin: GPIO02
  id: modbus1

modbus_controller:
  - id: modbusc1
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
# Modbus RS485 till here

mcp23s08:
  - id: 'mcp23xxx_hub'
    cs_pin: GPIO32
    deviceaddress: 0

# Individual outputs
output:
  - platform: gpio
    id: relay4
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 4
      number: 4
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay3
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 5
      number: 5
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay2
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 6
      number: 6
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay1
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 7
      number: 7
      mode: OUTPUT
      inverted: False

binary_sensor:
  - platform: gpio
    name: "Input 1"
    id: input1
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 3
      number: 3
      # One of INPUT or INPUT_PULLUP
      mode: INPUT
      inverted: True

  - platform: gpio
    id: input2
    name: "Input 2"
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 2
      number: 2
      # One of INPUT or INPUT_PULLUP
      mode: INPUT
      inverted: True

  - platform: gpio
    id: input3
    name: "Input 3"
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 1
      number: 1
      # One of INPUT or INPUT_PULLUP
      mode: INPUT
      inverted: True

  - platform: gpio
    id: input4
    name: "Input 4"
    pin:
      mcp23xxx: mcp23xxx_hub
      # Use pin number 0
      number: 0
      # One of INPUT or INPUT_PULLUP
      mode: INPUT
      inverted: True

light:
  - platform: esp32_rmt_led_strip
    name: "LED WS2812B"
    pin: GPIO0
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812