packages:
  common: !include ../common/esp32-wrover.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1

# Allow dimmable control of the backlight (pin GPIO4)
output:
  - platform: ledc
    pin: GPIO4
    id: gpio_04_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_04_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: ili9xxx
    model: st7789v
    dimensions:
      height: 240
      width: 135
      offset_height: 40
      offset_width: 52
    # Required or the colors are all inverted, and Black screen is White
    invert_colors: true
    id: screen
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    #brightness: 100%
    rotation: 270