modbus_controller:
  - id: modbusc1
    ## the Modbus device addr
    address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s
    command_throttle: 100ms
# Modbus RS485 till here
sensor:
  # - platform: modbus_controller
  #   modbus_controller_id: modbusc1
  #   name: "Device Adress"
  #   id: address
  #   custom_command: [0x00, 0x03, 0x40, 0x00, 0x00, 0x01]
  #   value_type: U_WORD
  # - platform: modbus_controller
  #   modbus_controller_id: modbusc1
  #   name: "input register"
  #   id: input
  #   custom_command: [0x01, 0x020, 0x00, 0x00, 0x00, 0x08]
  #   value_type: U_WORD
  
output:
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 0
    register_type: COIL
    id: modbus_out0
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 1
    register_type: COIL
    id: modbus_out1
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 2
    register_type: COIL
    id: modbus_out2
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 3
    register_type: COIL
    id: modbus_out3
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 4
    register_type: COIL
    id: modbus_out4
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 5
    register_type: COIL
    id: modbus_out5
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 6
    register_type: COIL
    id: modbus_out6
  - platform: modbus_controller
    modbus_controller_id: modbusc1
    address: 7
    register_type: COIL
    id: modbus_out7