esphome:
  # ...
  includes:
    - stream_server.h
    - stream_server.cpp

uart:
  id: uart_bus
  #  ...
  
custom_component:
  - lambda: |-
      auto stream_server = new StreamServerComponent(id(uart_bus));
      return {stream_server};