esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

safe_mode:

switch:
  # this provides for a possibility to restart from the web console or Home automation should we ever need it
  - platform: restart
    name: "${upper_devicename} Restart"
  - platform: safe_mode
    name: "${upper_devicename} Restart (Safe Mode)"

# Sensors with general information.
sensor:
  - platform: uptime
    name: "${upper_devicename} Uptime"
    id: uptime_sensor

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

time:
  - platform: homeassistant
    id: homeassistant_time