wifi:
  ssid: !secret ssid
  password: !secret wifipassword
  use_address: "${devicename}.iot.dragundo.net"
  reboot_timeout: 0s

sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${upper_devicename} Signal strength
    update_interval: 60s
    internal: true

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${upper_devicename} IP
    ssid:
      name: ${upper_devicename} SSID
    bssid:
      name: ${upper_devicename} BSSID