wifi:
  ssid: !secret ssid
  password: !secret wifipassword
  use_address: "${devicename}.iot.dragundo.net"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Hotspot"
    password: !secret fallback_wifipassword

sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${upper_devicename} Signal strength
    update_interval: 60s
    internal: true

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${upper_devicename} IP
    ssid:
      name: ${upper_devicename} SSID
    bssid:
      name: ${upper_devicename} BSSID